name: Release & Publish

on:
  push
  # push:
  #   tags:
  #     - 'v*'

jobs:
  # release:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Create Release
  #       id: create_release
  #       uses: actions/create-release@v1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #       with:
  #         tag_name: ${{ github.ref }}
  #         release_name: ${{ github.ref }}
  #         draft: false
  #         prerelease: false

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .npmrc file to publish to GitHub Packages
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"
          registry-url: "https://yarn .pkg.github.com"
          scope: "@jimsheen"
      - name: Create a .npmrc file for the github private repository
        uses: FerLuisxd/create-npmrc@3
        with:
          org_name: jimsheen
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install modules
        run: yarn  install
      - run: yarn  run pre:publish
      - name: Publish to GitHub Packages
        run: yarn  publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
